import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: '埃塞俄比亚 耶加雪菲',
    origin: '埃塞俄比亚',
    price: 128,
    image: '☕',
    description: '来自埃塞俄比亚耶加雪菲产区的精品咖啡豆，具有独特的柑橘和花香风味，口感清爽明亮。',
    roast: '浅度烘焙',
    flavor: ['柑橘', '花香', '蜂蜜'],
    weight: '227g',
  },
  {
    id: 2,
    name: '哥伦比亚 慧兰',
    origin: '哥伦比亚',
    price: 108,
    image: '☕',
    description: '哥伦比亚慧兰产区的高海拔咖啡豆，具有巧克力和坚果的醇厚风味，平衡感极佳。',
    roast: '中度烘焙',
    flavor: ['巧克力', '坚果', '焦糖'],
    weight: '227g',
  },
  {
    id: 3,
    name: '肯尼亚 AA',
    origin: '肯尼亚',
    price: 158,
    image: '☕',
    description: '肯尼亚最高等级的AA级咖啡豆，酸质明亮，带有黑醋栗和番茄般的复杂风味。',
    roast: '浅度烘焙',
    flavor: ['黑醋栗', '番茄', '柑橘'],
    weight: '227g',
  },
  {
    id: 4,
    name: '巴拿马 翡翠庄园 瑰夏',
    origin: '巴拿马',
    price: 388,
    image: '☕',
    description: '世界顶级咖啡豆之一，翡翠庄园的瑰夏品种，具有茉莉花、佛手柑和热带水果的精致风味。',
    roast: '浅度烘焙',
    flavor: ['茉莉花', '佛手柑', '热带水果'],
    weight: '100g',
  },
  {
    id: 5,
    name: '云南 保山',
    origin: '中国云南',
    price: 88,
    image: '☕',
    description: '来自中国云南保山产区的精品咖啡豆，具有红茶和红糖的温暖风味，性价比极高。',
    roast: '中度烘焙',
    flavor: ['红茶', '红糖', '坚果'],
    weight: '227g',
  },
  {
    id: 6,
    name: '危地马拉 安提瓜',
    origin: '危地马拉',
    price: 118,
    image: '☕',
    description: '危地马拉安提瓜火山土壤种植的咖啡豆，具有烟熏、可可和香料的丰富层次。',
    roast: '中深度烘焙',
    flavor: ['可可', '烟熏', '香料'],
    weight: '227g',
  },
  {
    id: 7,
    name: '曼特宁 黄金',
    origin: '印度尼西亚',
    price: 98,
    image: '☕',
    description: '印尼苏门答腊曼特宁黄金豆，醇厚浓郁，具有草本和雪松的独特风味。',
    roast: '深度烘焙',
    flavor: ['草本', '雪松', '黑巧克力'],
    weight: '227g',
  },
  {
    id: 8,
    name: '哥斯达黎加 蜜处理',
    origin: '哥斯达黎加',
    price: 138,
    image: '☕',
    description: '采用蜜处理工艺的哥斯达黎加咖啡豆，甜感突出，带有蜜桃和蜂蜜的甜美风味。',
    roast: '浅度烘焙',
    flavor: ['蜜桃', '蜂蜜', '香草'],
    weight: '227g',
  },
];
